name: fiap_test_flutter
description: "Projeto base em Flutter preparado para testes unitários, de widgets e E2E."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  mockito: ^5.4.4
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
